### ISSUE TITLE
[Feature] Use encryption to store SSH passwords and set a master password for decryption

### ISSUE THREAD

**Issue by MHNightCat** [grafviktor/goto#64]
You can set your own password
After the setting is completed, you can add a new password.
The password can probably be encrypted using aes256 (or better)
Every time you open ssh, it will check whether a password has been set and enter the password automatically.

I think this will be useful!

**Comment by grafviktor** [comment]
Hello @MHNightCat thank you very much for the idea. I thought about this feature, but deliberately decided to not go into this rabbit whole 🐰 The reason is very trivial - I don't have enough expertise in data security and therefore I cannot take a risk of storing users' passwords. Though, it can be quite straightforward to implement the functionality, it will be much much harder to do that properly. That's why I encourage people to use SSH keys instead. I hope you understand my concerns. 

Users' convenience and data security always go into opposite directions and we need to balance somewhere in between. 🙂

Roman.

**Comment by MHNightCat** [comment]
I totally understand. Thank you for your reply.
This cli app is really great!
